version: "2.1"
services:
    server:
     image: yandex/clickhouse-server
     environment:
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: secret
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9010:9009"
     
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
    client:
      image: yandex/clickhouse-client
      command: ['--host', 'server']
