version: "2.1"

services:
  oracle-xe:
    image: daggerok/oracle:xe
    shm_size: 1g
    environment:
      ORACLE_PWD: password
    ports:
    - "1521:1521"
    networks: [backing-services]

networks:
  backing-services:
    driver: bridge
