version: '2.1'
services:
  # default username: sa
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=123456789
     - MSSQL_AGENT_ENABLED=true
